name: Vdirsyncer Deployment Development
run-name: Vdirsyncer Deployment For Development Usage 🚀
on:
  push:
    branches:
      - "dev"

jobs:
  Vdirsyncer-Deployment-Development:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker Engine
        run: | 
          echo ${{ github.repository }}

      # https://github.com/marketplace/actions/checkout
      - name: Check Out Repository Code
        uses: actions/checkout@v4.2.2
        # with:
        #   repository: 'Bleala/Vdirsyncer-DOCKERIZED'
        #   ref: 'dev'

      # # https://github.com/marketplace/actions/checkout
      # - name: Check Out Repository Code
      #   uses: actions/checkout@v4.2.2
      #   with:
      #     repository: ${{ secrets.GIT_REPO_DEV }}

      # # https://github.com/marketplace/actions/docker-hub-description
      # - name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v4.0.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}
      #     short-description: "Vdirsyncer - sync calendars and addressbooks between servers and the local filesystem. DOCKERIZED!"

      # # https://docs.docker.com/engine/install/ubuntu/
      # # https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script
      # - name: Install Docker Engine
      #   run: | 
      #     curl -fsSL https://get.docker.com -o get-docker.sh
      #     sh ./get-docker.sh

      # # https://github.com/marketplace/actions/docker-setup-qemu
      # - name: Set Up QEMU
      #   uses: docker/setup-qemu-action@v3.3.0

      # # https://github.com/marketplace/actions/docker-setup-buildx
      # - name: Set Up Docker Buildx
      #   uses: docker/setup-buildx-action@v3.8.0

      # # https://github.com/marketplace/actions/docker-login#github-container-registry
      # - name: Login To Docker Hub
      #   uses: docker/login-action@v3.3.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # # https://github.com/marketplace/actions/docker-login#github-container-registry
      # - name: Login To GitHub Container Registry
      #   uses: docker/login-action@v3.3.0
      #   with:
      #     registry: ${{ secrets.GHCR_URL }}
      #     username: ${{ secrets.GHCR_USERNAME }}
      #     password: ${{ secrets.GHCR_TOKEN }}

      # # https://github.com/marketplace/actions/docker-login#github-container-registry
      # - name: Login To Gitea
      #   uses: docker/login-action@v3.3.0
      #   with:
      #     registry: ${{ secrets.LOCAL_URL }}
      #     username: ${{ secrets.LOCAL_USERNAME }}
      #     password: ${{ secrets.LOCAL_TOKEN }}

      # # https://github.com/marketplace/actions/build-and-push-docker-images
      # - name: Build And Push
      #   uses: docker/build-push-action@v6.11.0
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:dev
      #       ${{ secrets.GHCR_URL }}/${{ secrets.GHCR_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:dev
      #       ${{ secrets.LOCAL_URL }}/${{ secrets.LOCAL_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:dev

      # # https://github.com/marketplace/actions/ntfy_action
      # - name: Ntfy Notification Successful
      #   uses: niniyas/ntfy-action@v1.0.4
      #   if: success()
      #   with:
      #     url: '${{ secrets.NTFY_URL }}'
      #     topic: '${{ secrets.NTFY_TOPIC }}'
      #     tags: +1,partying_face,tada,action,successfully,completed
      #     title: 'Gitea Actions erfolgreich: ${{ env.GITHUB_REPOSITORY }} | ${{ env.GITHUB_REF_NAME }}'
      #     priority: 3
      #     details: Gitea Actions Workflow ist erfolgreich abgeschlossen.
      #     # Bearer Header notwendig in JSON --> https://docs.ntfy.sh/publish/#access-tokens
      #     headers: '${{ secrets.NTFY_HEADERS }}'
      #     actions: '[{"action": "view", "label": "Gitea öffnen", "url": "${{ secrets.GIT_URL }}/${{ env.GITHUB_REPOSITORY }}", "clear": true}]'
      #     icon: 'https://w7.pngwing.com/pngs/940/571/png-transparent-gitea-hd-logo.png'
      #     image: true

      # # https://github.com/marketplace/actions/ntfy_action
      # - name: Ntfy Notification Failed
      #   uses: niniyas/ntfy-action@v1.0.4
      #   if: failure()
      #   with:
      #     url: '${{ secrets.NTFY_URL }}'
      #     topic: '${{ secrets.NTFY_TOPIC }}'
      #     tags: -1,no_entry,skull,action,failed
      #     title: 'Gitea Actions fehlgeschlagen: ${{ env.GITHUB_REPOSITORY }} | ${{ env.GITHUB_REF_NAME }}'
      #     priority: 5
      #     details: Gitea Actions Workflow ist fehlgeschlagen!
      #     # Bearer Header notwendig in JSON --> https://docs.ntfy.sh/publish/#access-tokens
      #     headers: '${{ secrets.NTFY_HEADERS }}'
      #     actions: '[{"action": "view", "label": "Gitea öffnen", "url": "${{ secrets.GIT_URL }}/${{ env.GITHUB_REPOSITORY }}/actions", "clear": true}]'
      #     icon: 'https://w7.pngwing.com/pngs/940/571/png-transparent-gitea-hd-logo.png'
      #     image: true

      # # https://github.com/marketplace/actions/ntfy_action
      # - name: Ntfy Notification Cancelled
      #   uses: niniyas/ntfy-action@v1.0.4
      #   if: cancelled()
      #   with:
      #     url: '${{ secrets.NTFY_URL }}'
      #     topic: '${{ secrets.NTFY_TOPIC }}'
      #     tags: -1,cry,triangular_flag_on_post,action,cancelled
      #     title: 'Gitea Actions abgebrochen: ${{ env.GITHUB_REPOSITORY }} | ${{ env.GITHUB_REF_NAME }}'
      #     priority: 5
      #     details: Gitea Actions Workflow wurde abgebrochen!
      #     # Bearer Header notwendig in JSON --> https://docs.ntfy.sh/publish/#access-tokens
      #     headers: '${{ secrets.NTFY_HEADERS }}'
      #     actions: '[{"action": "view", "label": "Gitea öffnen", "url": "${{ secrets.GIT_URL }}/${{ env.GITHUB_REPOSITORY }}/actions", "clear": true}]'
      #     icon: 'https://w7.pngwing.com/pngs/940/571/png-transparent-gitea-hd-logo.png'
      #     image: true
