---
networks:
  vdirsyncer:
    driver: bridge

volumes:
  vdirsyncer:
    name: vdirsyncer
    driver: local

services:
  # Vdirsyncer - sync calendars and addressbooks between servers and the local filesystem. DOCKERIZED!
  # https://hub.docker.com/r/bleala/vdirsyncer
  app:
    image: bleala/vdirsyncer:latest
    container_name: vdirsyncer
    restart: unless-stopped
    networks:
      vdirsyncer: {}
    environment:
      # Optional: set your timezone, for correct container and log time, default to Europe/Vienna
      TZ: Europe/Vienna
      # Optional: # set to true for automatic discover, default to false
      AUTODISCOVER: true
      # Optional: # set to true for automatic sync, default to false
      AUTOSYNC: true
      # Optional: # set to true for automatic Vdirsyncer and dependencies updates on container startup, default to false
      AUTOUPDATE: true
      # Optional: # adjust autosync /-discover time, default to 15 minutes - */15 * * * *
      # Cron Time need to be set in Cron format - look here for generator https://crontab.guru/
      # Set CRON_TIME like that --> */15 * * * *
      CRON_TIME: '*/15 * * * *'
      # Optional: set to script path to automatically run your custom script before the cronjob `vdirsyncer` command(s), default to nothing
      PRE_SYNC_SCRIPT_FILE: ''
      # Optional: set to script path to automatically run your custom script after the cronjob `vdirsyncer` command(s), default to nothing
      POST_SYNC_SCRIPT_FILE: ''
      # Optional: default is normal output from supercronic
      SUPERCRONIC_FLAGS: ''
    volumes:
      - vdirsyncer:/vdirsyncer              # Docker Volume
      - /path/to/config:/vdirsyncer/config  # Vdirsyncer Config
      # Optional
      - /path/to/custom_before_script.sh:/vdirsyncer/custom_before_script.sh  # Custom Before Script
      - /path/to/custom_after_script.sh:/vdirsyncer/custom_after_script.sh  # Custom After Script
